### PR TITLE
Chart enchantments

### LINKED ISSUE #75: ClusterRole rules are too permissive
[role.yaml](https://github.com/resmoio/kubernetes-event-exporter/blob/master/charts/kubernetes-event-exporter/templates/role.yaml)

```yaml
{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
{{- end -}}
```

ClusterRole rules are too permissive! The service account does not need to be able to get, watch, list everything (e.g., secrets). The default should include only what is necessary for the software to function (i.e., events).

If we could configure the rules from the values.yaml that would be awesome.

### PR DESCRIPTION
**Pull request by jkroepke**
* Add ServiceMonitor
* Allow namespaced RBAC (works in combination with `namespace` on config)
* Allow to configure customized RBAC rules (fixes #75)
* Ensure that chart labels are defined on each object
* Ensure that kubernetes-event-exporter is restarted, if the config has been changes (https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments)
* Set kubernetes hardening by default
* Allow to define `imagePullSecrets` and `image.registry` form `Values.global`
* Add `topologySpreadConstraints` property
* Add `extraVolumes and extraVolumeMounts` (useful for manual AWS IRSA setup)
* Add `deploymentAnnotations`, `deploymentLabels` and `podLabels` (useful or reloader)
* Set `namespaceOverride` to empty by default.

### CODE REVIEW

**Comment by jkroepke** [comment]
@mustafaakin I would appreciate a review here, since you do #54

**Review by jacobredesign — APPROVED** [review]

**Comment by jacobredesign** [comment]
This looks great @jkroepke , was looking for this functionality regarding namespaces as our kube hosting provider doesn't give us cluster level api access so things like clusterroles are a non-starter.

**Comment by jkroepke** [comment]
@jacobredesign great that it l ooks good ob your side, too. 👍

@resmoio what did you think?

**Comment by jkroepke** [comment]
@mustafaakin should I split this PR into smaller pieces?

**Comment by miai10** [comment]
Does this MR fix this bug: https://github.com/resmoio/kubernetes-event-exporter/issues/106 ?

**Comment by jkroepke** [comment]
@miai10 The issues was recently introduced but this MR would also fix the issue you mentioned.

**Comment by jkroepke** [comment]
@jacobredesign @resmoio @mustafaakin I would appreciate a review here.

**Pull request merged**
