### PR TITLE
Add charts

### PR DESCRIPTION
**Pull request by zhan9san**
Related to #21

Could you please review the chart?

Please help create an branch,  `gh-pages` , which is required to store chart index file.

### CODE REVIEW

**Comment by zhan9san** [comment]
> It's still active, we %100 support it, but there have not been major PRs, and the project is fairly stable. Is there a specific PR you need to be merged and released, we can speed up the merging of them.

https://github.com/resmoio/kubernetes-event-exporter/issues/67#issuecomment-1454123407

@mustafaakin
Thanks for your work in this great project. Could you help review this PR?

**Comment by gsmith-sas** [comment]
@zhan9san How similar/different is this Helm chart from the [Bitinami one](https://github.com/bitnami/charts/tree/main/bitnami/kubernetes-event-exporter)?  I am not arguing for/against either Helm chart I am just trying to understand pros/cons of each.  Thanks!

**Comment by mustafaakin** [comment]
I do not use Helm, too much magic. But if it makes it easy to use this projects, I'd be happy to look at it though. I've merged a PR for kustomize #58 though. Can you make the related change in the README? @zhan9san

**Comment by mustafaakin** [comment]
Does it need a seperate gh-pages branch? We can serve it from the root as it seems. https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by zhan9san** [comment]
> Does it need a seperate gh-pages branch? We can serve it from the root as it seems. https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

@mustafaakin  Yes, it does. Thanks for your attention.

Here is the doc link, https://github.com/helm/chart-releaser-action#pre-requisites

The step 1, 2 and 4 have been implemented in this PR.

But the step 3 needs your help to do.

@gsmith-sas Thanks for your review. With this PR, we can control the chart release process at our own pace.

**Comment by mustafaakin** [comment]
Okay, I've created the branchç

**Review by mustafaakin — APPROVED** [review]

**Pull request merged**
