### PR TITLE
add loki receiver

### PR DESCRIPTION
**Pull request by navidshariaty**
I wanted to forward events to Loki but I had to create a proper request body as mentioned in Loki's documentation. so I used "LokiMsg" and "promtailStream" structs to push events to Loki

### CODE REVIEW

**Review by mddavisjha — APPROVED** [review]
I would love to get this into a release so we can get these events into Loki

**Comment by mruzicka** [comment]
Hi, please note that you can push events to Loki through the generic `webhook` sink, with a configuration similar to this:
```yaml
receivers:
  - name: loki
    webhook:
      endpoint: http://127.0.0.1:3100/loki/api/v1/push
      headers:
        User-Agent: kubernetes-event-exporter/1.1.0

      layout:
        # this is the layout expected by Loki as documented here:
        #   https://grafana.com/docs/loki/latest/api/#push-log-entries-to-loki
        streams:
          - stream:
              namespace: "{{ .InvolvedObject.Namespace }}"
              kind: "{{ .InvolvedObject.Kind }}"
              name: "{{ .InvolvedObject.Name }}"
              #foo: bar
            values:
              -
                # timestamp
                - "{{ mul .GetTimestampMs 1000 }}"
                # value
                - "{{- toJson . }}" # or anything which makes sense to you

route:
  routes:
    - match:
        - receiver: loki
```
This PR IMHO adds very little value and even removes some flexibility (the ability to decide whether the event timestamp should be re-used, or a [new one](https://github.com/resmoio/kubernetes-event-exporter/pull/50/files#diff-e947ab10599181b25b0214168f0bbc0ff59e24178b164d0bab7be650dfe0eee4R57) should be generated) in comparison to using the generic `webhook`.

**Comment by mddavisjha** [comment]
I actually gave up and got another option working just yesterday.  I decided to just use the grafana agent eventhandler (grafana/agent:main).  I figured that if I wanted to push to Loki, why not use a grafana agent to do it.

**Review by mddavisjha — CHANGES_REQUESTED** [review]
As posted in the conversation, there are ways to make it work without this PR (using webhooks), and also other products that will do the same thing (grafana/agent).
I believe this will rescind my approval.

**Comment by mustafaakin** [comment]
While it's trivial to do it with Webhook, its also nice to make it easy to use with less config. I'm also not very familiar with Loki. Is there anything missing? I did not get the point about timestamps @mruzicka

**Comment by jameshearttech** [comment]
Configure kubernetes-event-exporter to dump to stdout. Let promtail scrape the events and send them to loki.

https://www.reddit.com/r/devops/comments/10xxxwl/aggregating_kubernetes_events/

**Comment by stringang** [comment]
I am using `ghcr.io/opsgenie/kubernetes-event-exporter:v0.10` to dump to stdout. 
```yaml
route:
  routes:
  - match:
    - receiver: "loki"
receivers:
  - name: "loki"
    stdout:
      deDot: false
```

**Review by mustafaakin — APPROVED** [review]

**Comment by pizycki** [comment]
What version will feature loki sink?
I can see it's already merged to master, but no docker image has been released since yet (I guess).

**Pull request merged**
